// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73B_BP0ntOQ-yqCxZbjKAk8Ui7GajT0g',
    appId: '1:238745148522:web:91d07c07f4edf09026be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    authDomain: 'forexcompanion-e5a28.firebaseapp.com',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    measurementId: 'G-F24QVTGL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNE9HFodkZfyXfocDYW6RU60HbnlwCVM',
    appId: '1:238745148522:android:cbc474da2eb75bb426be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLL1ExM0cr0RRlLFVeHVAU3jqiC17IJI',
    appId: '1:238745148522:ios:7cde9828b36fd54326be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    iosBundleId: 'com.example.tajirFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLL1ExM0cr0RRlLFVeHVAU3jqiC17IJI',
    appId: '1:238745148522:ios:7cde9828b36fd54326be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    iosBundleId: 'com.example.tajirFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD73B_BP0ntOQ-yqCxZbjKAk8Ui7GajT0g',
    appId: '1:238745148522:web:073d0fb947e17e4326be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    authDomain: 'forexcompanion-e5a28.firebaseapp.com',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    measurementId: 'G-F93JBFJLT5',
  );
}
